version: '3.8'
## run complete: docker compose up -d
## docker compose down

## run test requirements: docker compose up -d redis postgres-test

services:
  app:
    container_name: secret_stash_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-local:5432/secret_stash_local
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres-local
    restart: unless-stopped

  redis:
    container_name: secret_stash-redis
    image: redis:7.2
    ports:
      - "6379:6379"

  postgres-local:
    container_name: secret_stash_postgres_local
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: secret_stash_local
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    container_name: secret_stash_postgres_test
    image: postgres:15
    ports:
      - "63490:5432"
    environment:
      POSTGRES_DB: secret_stash_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  postgres_data:
