version: '3.8'
## docker compose up -d
## docker compose down

services:
  mysql-test:
    container_name: secret_stash-mysql-test
    image: mysql:8.0
    ports:
      - "63490:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secret_stash_test

  mysql-local:
    container_name: secret_stash-mysql-local
    image: mysql:8.0
    ports:
      - "3106:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secret_stash_local

  redis:
    container_name: secret_stash-redis
    image: redis:7.2
    ports:
      - "6379:6379"