spring:
  application:
    name: secretstash
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/secret_stash_prod
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migrations

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: INFO

app:
  jwt:
    secret: W7N7NWhJby8o5vJ4eT0kydDNq93hUCZncnldFb5NChY=
    expirationMs: 86400000