spring:
  application:
    name: secretstash
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/secret_stash_prod
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migrations

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: db,redis
        liveness:
          include: ping

logging:
  level:
    org.hibernate.SQL: INFO

app:
  jwt:
    secret: W7N7NWhJby8o5vJ4eT0kydDNq93hUCZncnldFb5NChY=
    expirationMs: 86400000

# Swagger UI / OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    displayRequestDuration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json
