spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secret_stash_local
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migrations

logging:
  level:
    org.hibernate.SQL: DEBUG